# Generated by Django 3.0.4 on 2020-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='id',
        ),
        migrations.AlterField(
            model_name='boat',
            name='so_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
