# Generated by Django 3.1.3 on 2020-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0002_auto_20201125_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
