# Generated by Django 3.1.3 on 2020-12-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0003_boat_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='current_step',
            field=models.CharField(default='Not Started', max_length=12),
        ),
        migrations.AlterField(
            model_name='boat',
            name='so_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
