# Generated by Django 3.1.3 on 2021-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0004_auto_20201202_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.CharField(choices=[('1910-Bay', '1910 Bay Max'), ('2110-Bay', '2110 Bay Max'), ('2110T-Bay', '2110 Bay Max Tunnel'), ('2410-Bay', '2410 Bay Max'), ('2210-CB', '2210 Carolina Bay'), ('2300-CB', '2300 Carolina Bay'), ('2500-CB', '2500 Carolina Bay'), ('2700-CB', '2700 Carolina Bay'), ('180-CC', '180 CC Adventure'), ('198-CC', '198 CC Adventure'), ('210-CC', '210 CC Adventure'), ('220-CC', '220 CC Adventure'), ('232-CC', '232 CC Adventure'), ('256-CC', '256 CC Adventure'), ('272-CC', '272 CC Adventure'), ('280-CC', '280 CC Adventure'), ('292-CC', '292 CC Adventure'), ('320-CC', '320 CC Adventure'), ('210-LXF', '210 LXF'), ('220-LXF', '220 LXF'), ('232-LXF', '232 LXF'), ('256-LXF', '256 LXF')], default='180-CC', max_length=30),
        ),
    ]
