# Generated by Django 3.1.3 on 2021-03-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0008_auto_20210313_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='dealer_name',
        ),
    ]
