# Generated by Django 3.1.3 on 2021-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0010_auto_20210313_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='dealer_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
