# Generated by Django 3.1.3 on 2021-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0011_boat_dealer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='so_num',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
