# Generated by Django 3.1.3 on 2021-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0013_auto_20210313_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='so_num',
            field=models.IntegerField(default=211500, primary_key=True, serialize=False),
        ),
    ]
