# Generated by Django 3.1.3 on 2021-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0014_auto_20210313_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
