# Generated by Django 3.1.3 on 2021-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0015_boat_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='anticpated_Start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='motor',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
