# Generated by Django 3.1.3 on 2021-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0016_auto_20210313_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='anticpated_Start',
            new_name='anticipated_Start',
        ),
        migrations.AlterField(
            model_name='boat',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
