# Generated by Django 3.1.3 on 2021-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0018_auto_20210316_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='shipped',
        ),
        migrations.AddField(
            model_name='boat',
            name='ship',
            field=models.DateField(blank=True, null=True),
        ),
    ]
