# Generated by Django 3.1.3 on 2021-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0019_auto_20210404_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='qr_code_bool',
            field=models.BooleanField(default=False),
        ),
    ]
