# Generated by Django 3.1.3 on 2021-04-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0022_auto_20210404_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='qr_code',
        ),
    ]
