# Generated by Django 3.1.3 on 2021-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solookup', '0023_remove_boat_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='current_step',
            field=models.CharField(choices=[('Gel', 'Gel'), ('Skin', 'Skin'), ('Bulk', 'Bulk'), ('Floor', 'Floor'), ('Box', 'Box'), ('Pull', 'Pull'), ('Grind', 'Grind'), ('Cut', 'Cut'), ('Patch', 'Patch'), ('Hardware', 'Hardware'), ('Cap', 'Cap'), ('Foam', 'Foam'), ('Con', 'Con'), ('Motor', 'Motor'), ('Rig', 'Rig'), ('Upholstery', 'Upholstery'), ('CC', 'CC'), ('Inspection', 'Inspection'), ('Shipped', 'Shipped')], default='Not Started', max_length=12),
        ),
    ]
